services:
  filapress-nginx:
    container_name: filapress-nginx
    image: filapress-nginx
    volumes:
      - ../:/home/wwwroot/filapress
      - /home/wwwroot/filapress-core:/home/wwwroot/filapress-core
      - ./php/nginx-site.conf:/etc/nginx/conf.d/default.conf
      - ./php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./php/custom_php.ini:/usr/local/etc/php/conf.d/custom_php.ini
      - ./php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - /home/php/extension:/root/.vscode-server/extensions
      - /home/php/extension-insiders:/root/.vscode-server-insiders/extensions
    build:
      context: .
      dockerfile: ./php/dev.Dockerfile
    ports:
      - 31151:80
      - 31156:31156
    stdin_open: true
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2000M
    networks:
      filapress-net:
        ipv4_address: 172.16.115.11

  filapress-mysql:
    container_name: filapress-mysql
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: "Etc/UTC"
    ports:
      - 31152:3306
    volumes:
      - /home/mysql/filapress-mysql:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1000M
    networks:
      filapress-net:
        ipv4_address: 172.16.115.12

  filapress-phpmyadmin:
    container_name: filapress-phpmyadmin
    image: phpmyadmin
    ports:
      - 31153:80
    environment:
      - PMA_HOST=172.16.115.12
      - PMA_PORT=3306
      - PMA_USER=user
      - PMA_PASSWORD=pass
    depends_on:
      - filapress-mysql
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1000M
    networks:
      filapress-net:
        ipv4_address: 172.16.115.13

  filapress-testing-mysql:
    container_name: filapress-testing-mysql
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: "Etc/UTC"
    ports:
      - 31154:3306
    volumes:
      - /home/mysql/filapress-testing-mysql:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1000M
    networks:
      filapress-net:
        ipv4_address: 172.16.115.14

networks:
  filapress-net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.115.0/24
